{ album:
   { album_type: 'album',
     artists: [ [Object] ],
     available_markets:
      [ 'AD',
        'AE',
        'AR',
        'AT',
        'AU',
        'BE',
        'BG',
        'BH',
        'BO',
        'BR',
        'CA',
        'CH',
        'CL',
        'CO',
        'CR',
        'CY',
        'CZ',
        'DE',
        'DK',
        'DO',
        'DZ',
        'EC',
        'EE',
        'EG',
        'ES',
        'FI',
        'FR',
        'GB',
        'GR',
        'GT',
        'HK',
        'HN',
        'HU',
        'ID',
        'IE',
        'IL',
        'IS',
        'IT',
        'JO',
        'JP',
        'KW',
        'LB',
        'LI',
        'LT',
        'LU',
        'LV',
        'MA',
        'MC',
        'MT',
        'MX',
        'MY',
        'NI',
        'NL',
        'NO',
        'NZ',
        'OM',
        'PA',
        'PE',
        'PH',
        'PL',
        'PS',
        'PT',
        'PY',
        'QA',
        'RO',
        'SA',
        'SE',
        'SG',
        'SK',
        'SV',
        'TH',
        'TN',
        'TR',
        'TW',
        'US',
        'UY',
        'VN',
        'ZA' ],
     external_urls:
      { spotify: 'https://open.spotify.com/album/7dxKtc08dYeRVHt3p9CZJn' },
     href: 'https://api.spotify.com/v1/albums/7dxKtc08dYeRVHt3p9CZJn',
     id: '7dxKtc08dYeRVHt3p9CZJn',
     images: [ [Object], [Object], [Object] ],
     name: 'OK Computer',
     release_date: '1997-05-28',
     release_date_precision: 'day',
     total_tracks: 12,
     type: 'album',
     uri: 'spotify:album:7dxKtc08dYeRVHt3p9CZJn' },
  artists:
   [ { external_urls: [Object],
       href: 'https://api.spotify.com/v1/artists/4Z8W4fKeB5YxbusRsdQVPb',
       id: '4Z8W4fKeB5YxbusRsdQVPb',
       name: 'Radiohead',
       type: 'artist',
       uri: 'spotify:artist:4Z8W4fKeB5YxbusRsdQVPb' } ],
  available_markets:
   [ 'AD',
     'AE',
     'AR',
     'AT',
     'AU',
     'BE',
     'BG',
     'BH',
     'BO',
     'BR',
     'CA',
     'CH',
     'CL',
     'CO',
     'CR',
     'CY',
     'CZ',
     'DE',
     'DK',
     'DO',
     'DZ',
     'EC',
     'EE',
     'EG',
     'ES',
     'FI',
     'FR',
     'GB',
     'GR',
     'GT',
     'HK',
     'HN',
     'HU',
     'ID',
     'IE',
     'IL',
     'IS',
     'IT',
     'JO',
     'JP',
     'KW',
     'LB',
     'LI',
     'LT',
     'LU',
     'LV',
     'MA',
     'MC',
     'MT',
     'MX',
     'MY',
     'NI',
     'NL',
     'NO',
     'NZ',
     'OM',
     'PA',
     'PE',
     'PH',
     'PL',
     'PS',
     'PT',
     'PY',
     'QA',
     'RO',
     'SA',
     'SE',
     'SG',
     'SK',
     'SV',
     'TH',
     'TN',
     'TR',
     'TW',
     'US',
     'UY',
     'VN',
     'ZA' ],
  disc_number: 1,
  duration_ms: 264066,
  explicit: false,
  external_ids: { isrc: 'GBAYE9701368' },
  external_urls:
   { spotify: 'https://open.spotify.com/track/3SVAN3BRByDmHOhKyIDxfC' },
  href: 'https://api.spotify.com/v1/tracks/3SVAN3BRByDmHOhKyIDxfC',
  id: '3SVAN3BRByDmHOhKyIDxfC',
  is_local: false,
  name: 'Karma Police',
  popularity: 74,
  preview_url:
   'https://p.scdn.co/mp3-preview/5a09f5390e2862af1687f3671db3d6f84a813a45?cid=854b035079f24af5b991b2fcde5d04f6',
  track_number: 6,
  type: 'track',
  uri: 'spotify:track:3SVAN3BRByDmHOhKyIDxfC' }
Artist Name : undefined